Info:
  nom: STD23043 - TD1
  version: 1.0.0
Server:
  URL: https://localhost.STD23043.com
  Path:
    /customers:
      get:
        response:
          200:
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: "#/components/..."
components:
  schemas:
    Customer:
      type: object
      properties:
        name:
          type: String
        age:
          type: Integer