openapi: 3.0.0
info:
  title: Restaurant API
  version: 1.0.0
  description: API pour gérer les données des clients d'un restaurant.

paths:
  /customers:
    get:
      summary: Récupérer la liste des clients
      description: Renvoie une liste de tous les clients.
      responses:
        '200':
          description: Liste des clients récupérée avec succès.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    yearsOld:
                      type: integer
                      example: 25
        '400':
          description: Requête invalide.
        '500':
          description: Erreur interne du serveur.